### ISSUE TITLE
通过npm run start命令运行上传全景图点击test按钮一直是切换页面背景色

### ISSUE THREAD

**Issue by wuyouw** [IrisPro/KrpanoToolJS#2]
通过npm run start命令运行上传全景图点击test按钮一直是切换页面背景色
![1679831291802](https://user-images.githubusercontent.com/6253519/227773584-ac17b0ea-e215-470b-8670-416bd211e3e6.jpg)

**Comment by IrisPro** [comment]
不好意思。我已经更正了。你现在可以重试了。

**Comment by IrisPro** [comment]
你好。我已经修复了这个问题了，之前用于调试。【通过npm run start命令运行上传全景图点击test按钮一直是切换页面背景色 (Issue #2)】
非常感谢提出问题。




非洲难民
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IrisPro/KrpanoToolJS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月26日(星期天) 晚上7:48
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[IrisPro/KrpanoToolJS] 通过npm run start命令运行上传全景图点击test按钮一直是切换页面背景色 (Issue #2)





 
通过npm run start命令运行上传全景图点击test按钮一直是切换页面背景色

**Comment by wuyouw** [comment]
收到，我晚点试试
