### ISSUE TITLE
直接引用npm包编译报错

### ISSUE THREAD

**Issue by curx95** [IrisPro/KrpanoToolJS#3]
错误提示为
Compiled with problems:
WARNING in ./node_modules/_@krpano_js-tools@1.1.15@@krpano/js-tools/dist/index.esm.js 13:96247-96279
Module not found: Error: Can't resolve 'worker_threads' in 'K:\workspace\vr_edit5\node_modules\_@krpano_js-tools@1.1.15@@krpano\js-tools\dist'
我查了下，似乎是打包的时候，把项目里使用的worker api 打包成了node环境下的worker_threads

**Comment by IrisPro** [comment]
你好。这是一个警告。目前你可以忽略这个警告。我尝试去修复这个问题。
你这是用什么打包，webpack5？还是啥？

**Comment by curx95** [comment]
> 你好。这是一个警告。目前你可以忽略这个警告。我尝试去修复这个问题。 你这是用什么打包，webpack5？还是啥？

是的，是webpack5，"webpack": "^5.75.0"

**Comment by IrisPro** [comment]
临时处理方法，webpack配置参考：
`
module.exports = {
   devServer: {
          host: '0.0.0.0',
          port: '8050',
          static: {
              directory: path.resolve(__dirname, 'dist'),
          },
          client: {
              logging: 'error',
              overlay: false,
          },
      },
      stats: 'errors-only',
}`

**Comment by IrisPro** [comment]
它其实能用，你尝试配置一下，stats: 'errors-only'

**Comment by curx95** [comment]
好的，我尝试下，感谢

**Comment by IrisPro** [comment]
**webpack5临时处理方案，跳过这个包的解析：**
在webpack.config.js中加入如下代码：
```json
module.exports = {
  resolve: {
    fallback: {
      "worker_threads": false
    }
  }
}
```

**Comment by weijiatan456** [comment]
在webpack4我是这样处理这个警告：
```
......
configureWebpack: config => {
    config.externals = {
        ......
        'worker_threads':'worker_threads'
    };
},
......
```
