### ISSUE TITLE
请问一下demo中切出的图片压缩包中包含krpano代码是如何实现的

### ISSUE THREAD

**Issue by cyamoyed** [IrisPro/KrpanoToolJS#5]
demo中切片下载的压缩包中包含krpano的代码和文件，可以预览效果：
![image](https://user-images.githubusercontent.com/57441436/229029103-c5996312-2909-43e7-9a84-fa3b4959347d.png)
但是我通过github中示例代码操作后下载的压缩包中只有切片的图片：
![image](https://user-images.githubusercontent.com/57441436/229029243-50d90499-e18d-491e-8dec-f6590c2f0e75.png)
请问如何能将krpano的代码下载下来

**Comment by IrisPro** [comment]
很久不见，甚是想念：
1. demo是为了展示，在我的其它项目中：[链接](https://github.com/IrisPro/krpanoJSToolDemo)
2. 这个项目返回结果是有包含代码的，你仔细看文档可以看到；
3. 如何下载代码？我返回了字符串，你直接将字符串转为blob然后下载即可；
