### ISSUE TITLE
请求开放一个接口(关于切出来的cube全景图)

### ISSUE THREAD

**Issue by LcBaixiao** [IrisPro/KrpanoToolJS#6]
大佬有时间可以开放出一个接口吗 =>用来获取球形全景图文件切割出来的六张图的url或者base64

**Comment by IrisPro** [comment]
你好，之后可以考虑把图片路径放出来，之前没有这样的使用场景。
临时方法：
切图后，会返回一个结果，其中包含如下：
content: Blob; // 场景图片、缩略图、预览图 的Blob文件，可以用于上传到后台或者下载到本地
content 包含了所有的图片，这些都是必要的，已经被zip压缩了，如果想看，可以解压这个文件，如果想看url，可以看返回的xml代码，里面会记录图片的路径。

**Comment by LcBaixiao** [comment]
感谢您的回复 我还有个关于格式的问题。不支持png格式是因为无法正确将透明通道还原吗。

**Comment by IrisPro** [comment]
肯定可以支持，但是全景图是非透明的，为什么要用png格式呢？ 相同的图片，png格式比jpg大很多，完全不需要使用png。
我目前还没有遇到全景图一定要使用png格式的场景。
