### ISSUE TITLE
nodejs support

### ISSUE THREAD

**Issue by sunny-repo88** [IrisPro/KrpanoToolJS#8]
is this package able to run in nodejs?

**Comment by IrisPro** [comment]
Hello, currently it's not supported to use it in Node.js, but you can modify the source code to adapt it for Node.js usage. If you want to use it in Node.js, I recommend using the official krpanotools CLI from their website. It can achieve all the functionalities I provide, but my implementation is focused on browser usage to save server resources and bandwidth.

I have written another article where I introduced a portion of the krpanotools usage tutorial. You can take a look at that for reference.
https://juejin.cn/post/7257872746498310199
